/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Menus.java
 *
 * Created on 14/11/2011, 00:13:18
 */
package pergresp;

import java.awt.CardLayout;
import java.awt.GridLayout;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.IOException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Properties;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Müller
 */
public class Menus extends javax.swing.JFrame {
    static String sPerguntaCadastrada = "";
    static String label_pergunta = "";
    static String textoArea = "";
    NumberFormat formatador = new DecimalFormat("00");//formata colocando 0 a esquerda até 09
    static short numeroDaUltimaPergunta = 0;
    static int contador = 0;
    static short codigoPergunta = 0;
    /** Creates new form Menus */
    public Menus() {
        initComponents();
        setLocationRelativeTo(this);

        painelPerguntas.setVisible(false);
        painelEntrevistado.setVisible(false);
        painelRealizarEntrevista.setVisible(false);
        painelDadosEntrevistado.setVisible(false);
        painelRespostasEntrevistado.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPerguntas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_pergunta = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        lb_codigoDasPerguntas = new javax.swing.JLabel();
        painelEntrevistado = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tf_matricula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_nome = new javax.swing.JTextField();
        tf_telefone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_email = new javax.swing.JTextField();
        bt_salvarEntrevistado = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lb_mensagemEntrevistado = new javax.swing.JLabel();
        painelRealizarEntrevista = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lb_perguntas = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_resposta = new javax.swing.JTextArea();
        bt_salvarEntrevista = new javax.swing.JButton();
        lb_codigo = new javax.swing.JLabel();
        tf_codigoFornecido = new javax.swing.JTextField();
        bt_pesquisaCodigo = new javax.swing.JButton();
        tf_matriculaFornecida = new javax.swing.JTextField();
        painelDadosEntrevistado = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        painelRespostasEntrevistado = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mi_Perguntas = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelPerguntas.setBackground(new java.awt.Color(153, 153, 153));
        painelPerguntas.setPreferredSize(new java.awt.Dimension(500, 257));
        painelPerguntas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                painelPerderFoco(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel1.setText("Digite UMA pergunta");

        ta_pergunta.setColumns(20);
        ta_pergunta.setRows(5);
        jScrollPane1.setViewportView(ta_pergunta);

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarPerguntas(evt);
            }
        });
        jButton1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                perdeuPerguntas(evt);
            }
        });

        lb_codigoDasPerguntas.setFont(new java.awt.Font("Tahoma", 0, 12));
        lb_codigoDasPerguntas.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout painelPerguntasLayout = new javax.swing.GroupLayout(painelPerguntas);
        painelPerguntas.setLayout(painelPerguntasLayout);
        painelPerguntasLayout.setHorizontalGroup(
            painelPerguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPerguntasLayout.createSequentialGroup()
                .addGroup(painelPerguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPerguntasLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jLabel1))
                    .addGroup(painelPerguntasLayout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jButton1))
                    .addGroup(painelPerguntasLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPerguntasLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(lb_codigoDasPerguntas, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelPerguntasLayout.setVerticalGroup(
            painelPerguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPerguntasLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_codigoDasPerguntas, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addGap(33, 33, 33))
        );

        painelEntrevistado.setBackground(new java.awt.Color(153, 153, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel2.setText("Matricula:");

        tf_matricula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                verificaMatricula(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel3.setText("Nome:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel4.setText("Telefone:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel5.setText("Email:");

        bt_salvarEntrevistado.setText("Salvar");
        bt_salvarEntrevistado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarEntrevistado(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel9.setText("Preencha os dados abaixo:");

        lb_mensagemEntrevistado.setFont(new java.awt.Font("Tahoma", 0, 12));
        lb_mensagemEntrevistado.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout painelEntrevistadoLayout = new javax.swing.GroupLayout(painelEntrevistado);
        painelEntrevistado.setLayout(painelEntrevistadoLayout);
        painelEntrevistadoLayout.setHorizontalGroup(
            painelEntrevistadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEntrevistadoLayout.createSequentialGroup()
                .addGroup(painelEntrevistadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelEntrevistadoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painelEntrevistadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(painelEntrevistadoLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelEntrevistadoLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelEntrevistadoLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelEntrevistadoLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(painelEntrevistadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelEntrevistadoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bt_salvarEntrevistado)
                                .addGap(159, 159, 159))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelEntrevistadoLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 12, Short.MAX_VALUE)
                                .addGroup(painelEntrevistadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_mensagemEntrevistado, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                                    .addComponent(tf_matricula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelEntrevistadoLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel9)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        painelEntrevistadoLayout.setVerticalGroup(
            painelEntrevistadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelEntrevistadoLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(painelEntrevistadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(lb_mensagemEntrevistado, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelEntrevistadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelEntrevistadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelEntrevistadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bt_salvarEntrevistado)
                .addGap(28, 28, 28))
        );

        painelRealizarEntrevista.setBackground(new java.awt.Color(255, 102, 102));

        jLabel6.setText("Matricula:");

        jLabel8.setText("Resposta:");

        ta_resposta.setColumns(20);
        ta_resposta.setRows(5);
        jScrollPane2.setViewportView(ta_resposta);

        bt_salvarEntrevista.setText("Salvar");
        bt_salvarEntrevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarEntrevista(evt);
            }
        });

        lb_codigo.setText("Codigo da entrevista:");

        bt_pesquisaCodigo.setText("Pesquisar");
        bt_pesquisaCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pesquisaCodigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelRealizarEntrevistaLayout = new javax.swing.GroupLayout(painelRealizarEntrevista);
        painelRealizarEntrevista.setLayout(painelRealizarEntrevistaLayout);
        painelRealizarEntrevistaLayout.setHorizontalGroup(
            painelRealizarEntrevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelRealizarEntrevistaLayout.createSequentialGroup()
                .addGroup(painelRealizarEntrevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelRealizarEntrevistaLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(bt_salvarEntrevista))
                    .addGroup(painelRealizarEntrevistaLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(painelRealizarEntrevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelRealizarEntrevistaLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_matriculaFornecida, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lb_codigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_codigoFornecido, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt_pesquisaCodigo))
                            .addGroup(painelRealizarEntrevistaLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(painelRealizarEntrevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lb_perguntas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        painelRealizarEntrevistaLayout.setVerticalGroup(
            painelRealizarEntrevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelRealizarEntrevistaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(painelRealizarEntrevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lb_codigo)
                    .addComponent(tf_matriculaFornecida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_codigoFornecido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_pesquisaCodigo))
                .addGap(18, 18, 18)
                .addComponent(lb_perguntas, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(painelRealizarEntrevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelRealizarEntrevistaLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelRealizarEntrevistaLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(bt_salvarEntrevista)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        painelDadosEntrevistado.setBackground(new java.awt.Color(102, 102, 0));

        jLabel10.setBackground(new java.awt.Color(102, 255, 51));
        jLabel10.setForeground(new java.awt.Color(153, 255, 153));
        jLabel10.setText("Digite a matricula:");

        jButton2.setText("Pesquisar");

        jLabel11.setBackground(new java.awt.Color(102, 255, 51));
        jLabel11.setForeground(new java.awt.Color(153, 255, 153));
        jLabel11.setText("Nome:");

        jLabel12.setBackground(new java.awt.Color(102, 255, 51));
        jLabel12.setForeground(new java.awt.Color(153, 255, 153));
        jLabel12.setText("Telefone:");

        jLabel13.setBackground(new java.awt.Color(102, 255, 51));
        jLabel13.setForeground(new java.awt.Color(153, 255, 153));
        jLabel13.setText("Email:");

        javax.swing.GroupLayout painelDadosEntrevistadoLayout = new javax.swing.GroupLayout(painelDadosEntrevistado);
        painelDadosEntrevistado.setLayout(painelDadosEntrevistadoLayout);
        painelDadosEntrevistadoLayout.setHorizontalGroup(
            painelDadosEntrevistadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosEntrevistadoLayout.createSequentialGroup()
                .addGroup(painelDadosEntrevistadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadosEntrevistadoLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jButton2))
                    .addGroup(painelDadosEntrevistadoLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(painelDadosEntrevistadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(painelDadosEntrevistadoLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelDadosEntrevistadoLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelDadosEntrevistadoLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelDadosEntrevistadoLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        painelDadosEntrevistadoLayout.setVerticalGroup(
            painelDadosEntrevistadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosEntrevistadoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(painelDadosEntrevistadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDadosEntrevistadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(painelDadosEntrevistadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDadosEntrevistadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        painelRespostasEntrevistado.setBackground(new java.awt.Color(204, 255, 204));

        jLabel18.setBackground(new java.awt.Color(102, 255, 51));
        jLabel18.setText("Digite a matricula:");

        jButton6.setText("Pesquisar");

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        javax.swing.GroupLayout painelRespostasEntrevistadoLayout = new javax.swing.GroupLayout(painelRespostasEntrevistado);
        painelRespostasEntrevistado.setLayout(painelRespostasEntrevistadoLayout);
        painelRespostasEntrevistadoLayout.setHorizontalGroup(
            painelRespostasEntrevistadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelRespostasEntrevistadoLayout.createSequentialGroup()
                .addGroup(painelRespostasEntrevistadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelRespostasEntrevistadoLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(painelRespostasEntrevistadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(painelRespostasEntrevistadoLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(painelRespostasEntrevistadoLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jButton6)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        painelRespostasEntrevistadoLayout.setVerticalGroup(
            painelRespostasEntrevistadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelRespostasEntrevistadoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(painelRespostasEntrevistadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("Cadastrar");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        mi_Perguntas.setText("Perguntas");
        mi_Perguntas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcaoPerguntas(evt);
            }
        });
        jMenu1.add(mi_Perguntas);

        jMenuItem2.setText("Entrevistado");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcaoEntrevistado(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Realizar Entrevista");

        jMenuItem3.setText("Realizar Entrevista");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcaoRealizarEntrevista(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Relatorios");

        jMenuItem4.setText("Dados do Entrevistado");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcaoDadosEntrevistado(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("Respostas do Entrevistado");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcaoRespostasEntrevistado(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Sair");

        jMenuItem6.setText("Sair");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairOpcao(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelPerguntas, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(painelEntrevistado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(painelRealizarEntrevista, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(painelDadosEntrevistado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(painelRespostasEntrevistado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelPerguntas, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(painelEntrevistado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(painelRealizarEntrevista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(painelDadosEntrevistado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(painelRespostasEntrevistado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcaoPerguntas(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcaoPerguntas
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null, "clico foi");
        painelPerguntas.setVisible(true);
        painelEntrevistado.setVisible(false);
        painelRealizarEntrevista.setVisible(false);
        painelDadosEntrevistado.setVisible(false);
        painelRespostasEntrevistado.setVisible(false);
        
        ta_pergunta.requestFocus();
        
        //verifica numero do ultimo arquivo criado
        codigoPergunta = Utilitarios.carregaParametrosNumeroDeGrupoPerguntas(PerguntasRespostas.sNomeUsuario);
        
        //Utilitarios.mostraNaTela("Atenção!!! O conjunto das perguntas cadastradas tera codigo = " + //codigo das perguntas
          //                       formatador.format(++codigoPergunta));
        lb_codigoDasPerguntas.setText("Atenção!!! O conjunto das perguntas cadastradas tera codigo = " + //codigo das perguntas
                                 formatador.format(++codigoPergunta));
    }//GEN-LAST:event_opcaoPerguntas

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void opcaoEntrevistado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcaoEntrevistado
        // TODO add your handling code here:
        painelPerguntas.setVisible(false);
        painelEntrevistado.setVisible(true);
        painelRealizarEntrevista.setVisible(false);
        painelDadosEntrevistado.setVisible(false);
        painelRespostasEntrevistado.setVisible(false);       
        
    }//GEN-LAST:event_opcaoEntrevistado

    private void opcaoRealizarEntrevista(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcaoRealizarEntrevista
        // TODO add your handling code here:
        painelPerguntas.setVisible(false);
        painelEntrevistado.setVisible(false);
        painelRealizarEntrevista.setVisible(true);
        painelDadosEntrevistado.setVisible(false);
        painelRespostasEntrevistado.setVisible(false);
        
        
    }//GEN-LAST:event_opcaoRealizarEntrevista

    private void opcaoDadosEntrevistado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcaoDadosEntrevistado
        // TODO add your handling code here:
        painelPerguntas.setVisible(false);
        painelEntrevistado.setVisible(false);
        painelRealizarEntrevista.setVisible(false);
        painelDadosEntrevistado.setVisible(true);
        painelRespostasEntrevistado.setVisible(false);
        
        
    }//GEN-LAST:event_opcaoDadosEntrevistado

    private void opcaoRespostasEntrevistado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcaoRespostasEntrevistado
        // TODO add your handling code here:
        painelPerguntas.setVisible(false);
        painelEntrevistado.setVisible(false);
        painelRealizarEntrevista.setVisible(false);
        painelDadosEntrevistado.setVisible(false);
        painelRespostasEntrevistado.setVisible(true);
        
        
    }//GEN-LAST:event_opcaoRespostasEntrevistado

    private void salvarPerguntas(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarPerguntas
        // TODO add your handling code here:
        if (ta_pergunta.getText().equals("")) //se estiver vazio retorna
        {
                return;                
        }
        //JOptionPane.showMessageDialog(null, "ok");
        //short codigoPergunta = 1;
        NumberFormat formatador = new DecimalFormat("00");//formata colocando 0 a esquerda até 09
        //short numeroDaUltimaPergunta = 0;
        String perguntas[] = new String[100];
        PerguntasRespostas perguntasResposta1 = new PerguntasRespostas();
                
        //for (contador = 0; contador < (contador+1); contador++)
        //{   
        
            while(painelPerguntas.isVisible()) // enquanto painel for visivel, true
            {
                //codigoPergunta--;
                if (ta_pergunta.getText().equals("")) //se estiver vazio retorna
                {
                    return;                
                }       
                numeroDaUltimaPergunta = Utilitarios.carregaParametrosNumeroDaUltimaPergunta(numeroDaUltimaPergunta,
                                         formatador.format(codigoPergunta) + perguntasResposta1.sNomeUsuario);

                //String pergunta = JOptionPane.showInputDialog("Digite a pergunta");
                String pergunta = ta_pergunta.getText();

                // ++ antes de converte em String. formatador colocando 0 a esquerda
                //pega a pergunta concatena com numero coloca no vetor
                perguntas[contador] =  String.valueOf(formatador.format(++numeroDaUltimaPergunta)) +" "+ pergunta;
                Utilitarios.gravaPerguntas(numeroDaUltimaPergunta, Short.parseShort(formatador.format(codigoPergunta)) ,
                                            perguntasResposta1.sNomeUsuario, perguntas[contador]);//grava perguntas

                Utilitarios.mostraNaTela("Pergunta salva!");
                ta_pergunta.setText(""); //esvazeia caixa de cadastro de pergunta
                ta_pergunta.requestFocus(); // coloca o foco
                //continue;
            }           
             //Utilitarios.mostraNaTela("Atenção!!! O conjunto das perguntas cadastradas tera codigo = " + //codigo das perguntas
               //                  formatador.format(++codigoPergunta));
            //char cCadastrarOutraPergunta = (char) JOptionPane.showConfirmDialog(null,"Deseja "
              //      + "cadastrar outra pergunta", "Outra Pergunta?", JOptionPane.YES_NO_OPTION,
                //    JOptionPane.QUESTION_MESSAGE);// ? verde
           /* if(cCadastrarOutraPergunta == 0)
            {
                //pega o numero da ultima pergunta
                numeroDaUltimaPergunta = Utilitarios.carregaParametrosNumeroDaUltimaPergunta(numeroDaUltimaPergunta,
                                                formatador.format(codigoPergunta) + perguntasResposta1.sNomeUsuario); 
                //continue;// volta no for                                         
            }
            else
            {
                //pega o numero da ultima pergunta
               numeroDaUltimaPergunta = Utilitarios.carregaParametrosNumeroDaUltimaPergunta(numeroDaUltimaPergunta, formatador.format(codigoPergunta) + perguntasResposta1.sNomeUsuario);
               //sair = false;
               //break; // sai do for
            }*/                        

        //}        
    }//GEN-LAST:event_salvarPerguntas

    private void sairOpcao(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairOpcao
        // TODO add your handling code here:
        char cResposta = (char) JOptionPane.showConfirmDialog(null, "Deseja finalizar o Programa?","Sair?????",
                                    JOptionPane.YES_NO_OPTION);
                            if(cResposta == 0)
                            {
                                   System.exit(0);//sai do sistema
                            }
    }//GEN-LAST:event_sairOpcao

    private void salvarEntrevistado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarEntrevistado
        // TODO add your handling code here:
      // do
        //{
            String sMatricula = tf_matricula.getText();
            String sNome = tf_nome.getText();
            String sTelefone = tf_telefone.getText();
            String sEmail = tf_email.getText();
            if (sMatricula.equals("") || sNome.equals("") || sTelefone.equals("") || sEmail.equals("")) // algum campo vazio???
            {
                Utilitarios.mostraNaTela("Esqueceu de preencher algum campo");
                return;
            }
                //verifica se a matricula ja existe , telefone e email
                boolean retornoEntrevistado = Utilitarios.carregaParametrosDadosEntrevistado(sMatricula);//, sTelefone, sEmail);
                if (retornoEntrevistado == false)
                {
                    Utilitarios.gravaEntrevistados(sMatricula, sNome, sTelefone, sEmail);//grava entrevistado
                    Utilitarios.mostraNaTela("Entrevistado salvo");
                }
                else
                {
                    //Utilitarios.mostraNaTela("Entrevistado ja existente no sistema verifique a matricula telefone e e-mail");
                    lb_mensagemEntrevistado.setText("Entrevistado ja existente no sistema verifique a matricula!!!");
                    //sair = false;
                 //   break;
                }

                /*char cOutroEntrevistado = (char) JOptionPane.showConfirmDialog(null, "Deseja cadastrar outro pessoa para entrevistar",
                        "aiaiaiaiaiaia",JOptionPane.YES_NO_OPTION);
                if(cOutroEntrevistado == 0)
                {
                   sair = true;
                }
                else
                {
                   sair = false;
                }                        
            }
            while(sair == true);*/
    }//GEN-LAST:event_salvarEntrevistado

    private void perdeuPerguntas(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_perdeuPerguntas
        // TODO add your handling code here:
        //mi_Perguntas.isVisible();
    }//GEN-LAST:event_perdeuPerguntas

    private void painelPerderFoco(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_painelPerderFoco
        // TODO add your handling code here:
//        NumberFormat formatador = new DecimalFormat("00");//formata colocando 0 a esquerda até 09
  //      Utilitarios.mostraNaTela("Atenção!!! O conjunto das perguntas cadastradas tera codigo = " + //codigo das perguntas
    //                             formatador.format(++codigoPergunta));
        
    }//GEN-LAST:event_painelPerderFoco

    private void verificaMatricula(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_verificaMatricula
        // TODO add your handling code here:
        //tf_matricula.setFocusable(true);
        if (!tf_matricula.getText().equals(""))
        {
            String sMatricula = tf_matricula.getText();
            boolean retornoEntrevistado = Utilitarios.carregaParametrosDadosEntrevistado(sMatricula);//, sTelefone, sEmail);
                if (retornoEntrevistado == true)
                {
                    lb_mensagemEntrevistado.setText("Numero de matricula ja cadastrado");
                }
                else
                {
                    lb_mensagemEntrevistado.setText("");
                }
        }
    }//GEN-LAST:event_verificaMatricula

    private void bt_pesquisaCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pesquisaCodigoActionPerformed
        // TODO add your handling code here:
        boolean bMatriculaExiste = Utilitarios.carregaParametrosDadosEntrevistado(tf_matriculaFornecida.getText());//, "", "");
        if (bMatriculaExiste == true)
        {
            //quer dizer que a matricula existe
            //String sCodigoFornecido = JOptionPane.showInputDialog("Digite o codigo da entrevista");
            //String sCodigoFornecido = pegaInformação.next();//não pego em short para poder tratar o erro no metodo
            
            //verifica codigo de pergunta e ja pega a respostas e grava por outro metodo
            boolean bCodigoexiste = carregaParametrosNumeroDeGrupoPerguntasExiste(tf_matriculaFornecida.getText(),
                    tf_codigoFornecido.getText(), PerguntasRespostas.sNomeUsuario);
            
            //lb_perguntas.setText(label_pergunta);
            //ta_resposta.setText(textoArea);
            
            if (bCodigoexiste == true)
            {
                //quer dizer q o grupo de perguntas existe
                Utilitarios.mostraNaTela("Entrevista realizada!!");
                //sair = false;
            }
            else
            {
                Utilitarios.mostraNaTela("Codigo de grupo de perguntas não existe, cadastre as perguntas para realizar a entrevista");
                //sair = false;
            }
        }
        else
        {
            Utilitarios.mostraNaTela("Matricula não existe, cadastre o entrevistado para realizar a entrevista");
            //sair = false;
        }
    }//GEN-LAST:event_bt_pesquisaCodigoActionPerformed

    private void salvarEntrevista(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarEntrevista
        // TODO add your handling code here:
        carregaParametrosNumeroDeGrupoPerguntasExiste(tf_matriculaFornecida.getText(),
                    tf_codigoFornecido.getText(), PerguntasRespostas.sNomeUsuario);
        
    }//GEN-LAST:event_salvarEntrevista

    public boolean carregaParametrosNumeroDeGrupoPerguntasExiste(String sMatricula, String sCodigo, String sUsuario) // existe grupo de pergunta
    {
        NumberFormat formatador = new DecimalFormat("00");
        try
        {
            Scanner pegaInformacao = new Scanner(System.in);
            short shCodigo = Short.parseShort(sCodigo);
            Properties config = new Properties();
            String arquivo = "perguntas\\"+ formatador.format(shCodigo)+sUsuario+".txt";
            BufferedReader input = new BufferedReader(new FileReader(arquivo));
            config.load(new FileInputStream(arquivo));
            sPerguntaCadastrada = "";

            while(input.ready())
            {
                sPerguntaCadastrada = input.readLine();
                //sPerguntaCadastrada = sPerguntaCadastrada;//.substring(18, sPerguntaCadastrada.length());
                lb_perguntas.setText(sPerguntaCadastrada);//joga pergunta na label
                //retornaCasoCampoVazio();
                //Thread.sleep(500);
                    if (ta_resposta.getText().equals(""))
                    {
                        break; 
                    }
                    else
                    {
                        ta_resposta.setText("");
                        String sResposta = ta_resposta.getText();// reposta que foi escrita na text area
                        Utilitarios.gravaRespostasEntrevistados(sMatricula, sCodigo, sPerguntaCadastrada, sResposta);

                    }
               continue;
                //salvarEntrevista(null);
            }
            input.close();
            return true;
        }
        catch(IOException eeerro)
        {
            return false;
        }
        catch (IllegalArgumentException erro)//na hora de digitar o codigo da entrevista
        {
            Utilitarios.mostraNaTela("Atenção!!! Digite o codigo usando numeros");
            return false;
        }
    }
    public void retornaCasoCampoVazio()
    {
        if (lb_perguntas.getText().equals(""))
        {
            return;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Menus().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_pesquisaCodigo;
    private javax.swing.JButton bt_salvarEntrevista;
    private javax.swing.JButton bt_salvarEntrevistado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel lb_codigo;
    private javax.swing.JLabel lb_codigoDasPerguntas;
    private javax.swing.JLabel lb_mensagemEntrevistado;
    private javax.swing.JLabel lb_perguntas;
    private javax.swing.JMenuItem mi_Perguntas;
    private javax.swing.JPanel painelDadosEntrevistado;
    private javax.swing.JPanel painelEntrevistado;
    private javax.swing.JPanel painelPerguntas;
    private javax.swing.JPanel painelRealizarEntrevista;
    private javax.swing.JPanel painelRespostasEntrevistado;
    private javax.swing.JTextArea ta_pergunta;
    private javax.swing.JTextArea ta_resposta;
    private javax.swing.JTextField tf_codigoFornecido;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_matricula;
    private javax.swing.JTextField tf_matriculaFornecida;
    private javax.swing.JTextField tf_nome;
    private javax.swing.JTextField tf_telefone;
    // End of variables declaration//GEN-END:variables
}
