/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PerguntasRespostas.java
 *
 * Created on 13/11/2011, 22:35:11
 */
package pergresp;

import java.awt.GraphicsConfiguration;
import java.awt.Image;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Müller
 */
public class PerguntasRespostas extends javax.swing.JFrame {

    static String sNomeUsuario  = "";
    /** Creates new form PerguntasRespostas */
    public PerguntasRespostas() {
        initComponents();
        setLocationRelativeTo(null); //centralisa janela
        //getContentPane().add(new JLabel(new ImageIcon("C:\\Users\\Müller\\Desktop\\cafe_xicara.jpg")));
        //setSize(300,300); // tamanho da tela
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_usuario = new javax.swing.JTextField();
        pf_senha = new javax.swing.JPasswordField();
        bt_entrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);

        jLabel1.setText("Usuario:");

        jLabel2.setText("Senha:");

        tf_usuario.setText("Digite seu usuario");
        tf_usuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focoSeleciona(evt);
            }
        });

        bt_entrar.setText("Entrar");
        bt_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_entrarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Perg?");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Resp!");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pf_senha)
                                    .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(bt_entrar)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pf_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(bt_entrar)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_entrarActionPerformed
        // TODO add your handling code here:
        Menus menu = new Menus();
        if (tf_usuario.getText().equals("") && String.valueOf(pf_senha.getPassword()).equals(""))
        {
            JOptionPane.showMessageDialog(null, "Preencha os campos");
        }
        else if(tf_usuario.getText().equals(""))
        {
            Utilitarios.mostraNaTela("Por favor preencha o campo usuario");
        }
        else if(String.valueOf(pf_senha.getPassword()).equals(""))
        {
            Utilitarios.mostraNaTela("Por favor preencha o campo senha");
        }
        else
        {
                   // boolean confirmacaoErrada = true;            
                    boolean retornoUsuario = Utilitarios.criarDiretorio("usuarios");// cria pasta usuarios senão existir
                    boolean retornoPerguntas = Utilitarios.criarDiretorio("perguntas");// cria pasta perguntas senão existir
                    boolean retornoEntrevistados = Utilitarios.criarDiretorio("pessoasEntrevistadas");// cria pasta pessoasEntrevistadas senão existir
                    boolean retornoRespostas = Utilitarios.criarDiretorio("respostas");// cria pasta respostas senão existir
                    Utilitarios.mostraNaTela((retornoUsuario == true && retornoPerguntas == true && retornoEntrevistados == true &&
                            retornoRespostas == true) ? "Pastas criadas (Banco de dados)" : "Diretorios ja criados");
                       
                    boolean existeS_N = Utilitarios.carregaParametros(tf_usuario.getText()); // existe arquivo de usuarios SIM NÂO

                    if (existeS_N == false)
                    {
                             char confirmacao = (char) JOptionPane.showConfirmDialog(null, "O usuario >> " + tf_usuario.getText() + " << ainda não esta cadastrado\n"
                             + "Deseja realizar o cadastro??", "Cadastrar usuario?", JOptionPane.YES_NO_OPTION);
                             if (confirmacao == 0)//cadatra usuario
                             {
                                    Utilitarios.gravaArquivo(tf_usuario.getText(), String.valueOf(pf_senha.getPassword()), String.valueOf(pf_senha.getPassword()));//grava os dados do novo usuario
                                    Utilitarios.mostraNaTela("Usuario: " + tf_usuario.getText() + "\nSenha: " + String.valueOf(pf_senha.getPassword()) + 
                                    "\nCadastrado!!! Parabens");
                                    setVisible(false); //some tela de validação
                                    
                                    menu.setVisible(true);
                                    
                                    //Menu1a5.opcoes(tf_usuario.getText());// mostra o menu do sistema
                             }
                             else//não cadastra usuario
                             {
                                    Utilitarios.mostraNaTela("Usuario NÃO cadastrado!!");
                             }
                             }
                    else//O USUARIO JA EXISTE logo sua senha e a mesma coisa q a confirmação da senha, metodo gravarArquivo
                    {
                             sNomeUsuario = tf_usuario.getText();
                             boolean senhaCorreta = Utilitarios.carregaParametros(tf_usuario.getText(), String.valueOf(pf_senha.getPassword()));
                             if (senhaCorreta == true)
                             {
                                    Utilitarios.carregaParametrosDataHora(tf_usuario.getText()); //mostra ultimo acesso
                                    
                                    //grava usuario senha confirmação da senha e ultimo acesso
                                    Utilitarios.gravaArquivo(tf_usuario.getText(), String.valueOf(pf_senha.getPassword()), String.valueOf(pf_senha.getPassword()));
                                    setVisible(false);//some tela de validação
                                    menu.setVisible(true);
                                    //Menu1a5.opcoes(tf_usuario.getText()); // joga a opção para o metodo
                             }
                             else
                             {
                                    Utilitarios.mostraNaTela("Senha Incorreta \nTente Novamente");
                                    pf_senha.requestFocus();
                                    pf_senha.selectAll();
                             }
                    }
            }            
        
    }//GEN-LAST:event_bt_entrarActionPerformed

    private void focoSeleciona(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focoSeleciona
        // TODO add your handling code here:
        tf_usuario.selectAll();
        pf_senha.selectAll();
    }//GEN-LAST:event_focoSeleciona

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerguntasRespostas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerguntasRespostas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerguntasRespostas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerguntasRespostas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PerguntasRespostas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_entrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField pf_senha;
    private javax.swing.JTextField tf_usuario;
    // End of variables declaration//GEN-END:variables
    
}
