import com.sun.xml.internal.ws.api.streaming.XMLStreamReaderFactory.Default;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import java.io.File;
import java.io.IOException;

import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;
import jxl.Cell;
import jxl.Sheet;
import jxl.Workbook;
import jxl.read.biff.BiffException;
/**
 *
 * @author Müller
 */
public class Administracao_Chamado extends javax.swing.JFrame 
{
    static  DefaultTableModel dtm = null;
    static ArrayList celulas = new ArrayList();    
    static int linhas = 0;

    //static JTable ta_tabela = new JTable();
    /** Creates new form Administracao_Chamado */
    public Administracao_Chamado()
    {
        initComponents();
        dtm = (DefaultTableModel) ta_tabela.getModel();
        setLocationRelativeTo(null);// centraliza tela
        setExtendedState(JFrame.MAXIMIZED_BOTH); //maximiza a tela
        pa_Oi.setVisible(false); // esconde painel   

        preencheTabela();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pa_Oi = new javax.swing.JPanel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        tf_pesquisa = new javax.swing.JTextField();
        bt_pesquisar = new javax.swing.JButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_tabela = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pa_Oi.setBackground(new java.awt.Color(255, 255, 102));

        jRadioButton3.setText("Protocolo");

        jLabel1.setText("Pesquisar por:");

        jRadioButton5.setText("Hora");

        bt_pesquisar.setText("Pesquisar");
        bt_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pesquisarActionPerformed(evt);
            }
        });

        jRadioButton4.setText("Data");

        jRadioButton2.setText("Local");

        jRadioButton1.setText("Link");

        jRadioButton6.setText("Observação");

        jButton1.setText("NOvo Chamado");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ta_tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Link", "Local", "Atendente", "Protocolo", "Data", "Hora", "Defeito", "Observacao"
            }
        ));
        jScrollPane1.setViewportView(ta_tabela);

        javax.swing.GroupLayout pa_OiLayout = new javax.swing.GroupLayout(pa_Oi);
        pa_Oi.setLayout(pa_OiLayout);
        pa_OiLayout.setHorizontalGroup(
            pa_OiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pa_OiLayout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(jButton1)
                .addContainerGap(532, Short.MAX_VALUE))
            .addGroup(pa_OiLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pa_OiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pa_OiLayout.createSequentialGroup()
                        .addGroup(pa_OiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton6)
                            .addComponent(jRadioButton5)
                            .addComponent(jRadioButton4)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 575, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pa_OiLayout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addGap(94, 94, 94)
                        .addComponent(tf_pesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_pesquisar)))
                .addGap(109, 109, 109))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE)
        );
        pa_OiLayout.setVerticalGroup(
            pa_OiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pa_OiLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pa_OiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pa_OiLayout.createSequentialGroup()
                        .addGroup(pa_OiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jRadioButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton6))
                    .addGroup(pa_OiLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(pa_OiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_pesquisar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("Chamado");

        jMenuItem1.setText("Oi");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Itautec");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sobre");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pa_Oi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pa_Oi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-878)/2, (screenSize.height-444)/2, 878, 444);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        pa_Oi.setVisible(true);        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        novaLinha();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bt_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pesquisarActionPerformed
        // TODO add your handling code here:
        String sConsulta = tf_pesquisa.getText(), sRegistro = "";
        
        ta_tabela.selectAll();
        for (int iLinha = 0; iLinha < linhas; iLinha++)
        {
            for (int iColunas = 0; iColunas < 8; iColunas++)
            {
                ///////JOptionPane.showMessageDialog(null, "contador = " + iLinha + "\nLinhas = " + linhas * 8);
                sRegistro = ta_tabela.getModel().getValueAt(iLinha, iColunas).toString();
                //////JOptionPane.showMessageDialog(null, "reg = " + sRegistro);
                if (sConsulta.equals(sRegistro))
                {
                    
                }
                else
                {
                   // ta_tabela.setValueAt(ta_tabela.getSelectedRow(), contador, contador).clearSelection();
                }
            }
        }        
    }//GEN-LAST:event_bt_pesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administracao_Chamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administracao_Chamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administracao_Chamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administracao_Chamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
//                new Administracao_Chamado().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_pesquisar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pa_Oi;
    public static javax.swing.JTable ta_tabela;
    private javax.swing.JTextField tf_pesquisa;
    // End of variables declaration//GEN-END:variables
    public static void preencheTabela() 
    {    
        {
           dtm = (DefaultTableModel) ta_tabela.getModel();
            /**
            * Carrega a planilha
            */
            Workbook workbook = null;
            try 
            {
                workbook = Workbook.getWorkbook(new File("exemplo.xls"));
            } 
            catch (IOException ex) 
            {
                JOptionPane.showMessageDialog(null, "Não foi possivel ler exemplo.xls");
                Logger.getLogger(Administracao_Chamado.class.getName()).log(Level.SEVERE, null, ex);
            } 
            catch (BiffException ex) 
            {
                JOptionPane.showMessageDialog(null, "Não foi possivel ler exemplo.xls BiffException");
                Logger.getLogger(Administracao_Chamado.class.getName()).log(Level.SEVERE, null, ex);
            }
            /**
            * Aqui é feito o controle de qual aba do xls 
            * será realiza a leitura dos dados
            */
            Sheet sheet = workbook.getSheet(0);

            /**
            * Numero de linhas com dados do xls
            */
            linhas = sheet.getRows();

            for(int i = 0; i < linhas; i++)
            {
                Cell celula1 = sheet.getCell(0, i);
                Cell celula2 = sheet.getCell(1, i);
                Cell celula3 = sheet.getCell(2, i);
                Cell celula4 = sheet.getCell(3, i);
                Cell celula5 = sheet.getCell(4, i);
                Cell celula6 = sheet.getCell(5, i);
                Cell celula7 = sheet.getCell(6, i);
                Cell celula8 = sheet.getCell(7, i);
                
                novaLinha();                
                
                dtm.setValueAt(celula1.getContents().toString(), i, 0);
                dtm.setValueAt(celula2.getContents().toString(), i, 1);
                dtm.setValueAt(celula3.getContents().toString(), i, 2);
                dtm.setValueAt(celula4.getContents().toString(), i, 3);
                dtm.setValueAt(celula5.getContents().toString(), i, 4);
                dtm.setValueAt(celula6.getContents().toString(), i, 5);
                dtm.setValueAt(celula7.getContents().toString(), i, 6);
                dtm.setValueAt(celula8.getContents().toString(), i, 7);
                
             //dtm.getValueAt(i, i)   
            }
            workbook.close(); //fecha o arquivo exemplo.xls
        }
    }
    public static void novaLinha()
    {
        int numero_linhas = ta_tabela.getRowCount();//conta registros
        
        //dtm.addRow(new Object[]{"", "", "", "", "", "", "", ""});  
        dtm.insertRow(numero_linhas, new Object []{"", "", "", "", "", "", "", ""});
    }
}