/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on 01/11/2011, 01:39:23
 */
package janelagraficas;

import java.util.Scanner;
import javax.swing.JOptionPane;
/**
 * @author Müller
 */
public class NewJFrame extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
        setLocation(640, 100);//onde a tela nasce
        setResizable(false);//não deixa redimensionar tela
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lb_usuario = new javax.swing.JLabel();
        lb_senha = new javax.swing.JLabel();
        tf_usuario = new javax.swing.JTextField();
        bt_entrar = new javax.swing.JButton();
        tf_senha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setToolTipText("");

        jLabel1.setBackground(new java.awt.Color(255, 255, 153));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel1.setForeground(new java.awt.Color(102, 255, 0));
        jLabel1.setText("Müller... Programa de perguntas e respostas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addContainerGap())
        );

        lb_usuario.setText("Usuario: ");

        lb_senha.setText("Senha: ");

        tf_usuario.setText("Digite seu nome de usuario");
        tf_usuario.setToolTipText("Digite seu nome de usuario");
        tf_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_usuarioActionPerformed(evt);
            }
        });
        tf_usuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                foco(evt);
            }
        });

        bt_entrar.setBackground(new java.awt.Color(0, 0, 0));
        bt_entrar.setFont(new java.awt.Font("Tahoma", 1, 14));
        bt_entrar.setForeground(new java.awt.Color(255, 255, 255));
        bt_entrar.setText("Entrar");
        bt_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_entrarActionPerformed(evt);
            }
        });
        bt_entrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                enter(evt);
            }
        });

        tf_senha.setToolTipText("Digite sua senha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_usuario)
                    .addComponent(lb_senha))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_entrar)
                    .addComponent(tf_senha)
                    .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_usuario)
                    .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_senha)
                    .addComponent(tf_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(bt_entrar)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_entrarActionPerformed
        //Scanner pegaInformacao = new Scanner(System.in);
            //Utilitarios.mostraNaTela((tf_usuario.getText().equals("")) ? "Por favor preencha o campo usuario" : null);
            //Utilitarios.mostraNaTela((tf_senha.getText().equals("")) ? "Por favor preencha o campo senha" : null);
            if(tf_senha.getText().equals("") && tf_usuario.getText().equals(""))
            {
                Utilitarios.mostraNaTela("Por favor preencha os campos");
                tf_usuario.requestFocus();
            }
            else if(tf_usuario.getText().equals(""))
            {
                Utilitarios.mostraNaTela("Por favor preencha o campo usuario");
            }
            else if(tf_senha.getText().equals(""))
            {
                Utilitarios.mostraNaTela("Por favor preencha o campo senha");
            }
            else
            {
                    boolean confirmacaoErrada = true;            
                    boolean retornoUsuario = Utilitarios.criarDiretorio("usuarios");// cria pasta usuarios senão existir
                    boolean retornoPerguntas = Utilitarios.criarDiretorio("perguntas");// cria pasta perguntas senão existir
                    boolean retornoEntrevistados = Utilitarios.criarDiretorio("pessoasEntrevistadas");// cria pasta pessoasEntrevistadas senão existir
                    boolean retornoRespostas = Utilitarios.criarDiretorio("respostas");// cria pasta respostas senão existir
                    Utilitarios.mostraNaTela((retornoUsuario == true && retornoPerguntas == true && retornoEntrevistados == true &&
                            retornoRespostas == true) ? "Pastas criadas (Banco de dados)" : "Diretorios ja criados");
                       //do
                       //{
                            //Utilitarios.mostraNaTela("Digite o nome do usuario CADASTRADO"); // e ja verifica se o usuario existe
                            //String sNomeUsuario = pegaInformacao.nextLine();
                            boolean existeS_N = Utilitarios.carregaParametros(tf_usuario.getText()); // existe arquivo de usuarios SIM NÂO
                            //String sSenha = "", sConfirmaSenha = "";                    

                            if (existeS_N == false)
                            {
                                char confirmacao = (char) JOptionPane.showConfirmDialog(null, "O usuario >> " + tf_usuario.getText() + " << ainda não esta cadastrado\n"
                                        + "Deseja realizar o cadastro??", "Cadastrar usuario?", JOptionPane.YES_NO_OPTION);
                                if (confirmacao == 0)//cadatra usuario
                                {
                                    //Utilitarios.mostraNaTela("Digite o nome do usuario para realiazar o Cadastro SEM ESPAÇOS");
                                    //sNomeUsuario = pegaInformacao.nextLine();

                                    //Utilitarios.mostraNaTela("Digite a senha para realizar o cadastro");
                                    //sSenha = pegaInformacao.nextLine();

                                    //Utilitarios.mostraNaTela("Digite a senha novamente SEM ESPAÇOS");
                                    //sConfirmaSenha = pegaInformacao.nextLine();
                                    //if(sConfirmaSenha.equals(sSenha))
                                    //{
                                        Utilitarios.gravaArquivo(tf_usuario.getText(), tf_senha.getText(), tf_senha.getText());//grava os dados do novo usuario
                                        //sNomeUsuario = pegaInformacao.next();
                                        //sSenha = pegaInformacao.next();
                                        //sConfirmaSenha = pegaInformacao.next();
                                        
                                        Utilitarios.mostraNaTela("Usuario: " + tf_usuario.getText() + "\nSenha: " + tf_senha.getText() + 
                                                "\nCadastrado!!! Parabens");
                                        //Utilitarios.mostraMenuDe5opcoes();// mostra o menu do sistema
                                        //byte sMenuOpcao = pegaInformacao.nextByte();//pega a opção do usuario em byte
                                        Menu1a5.opcoes(tf_usuario.getText());// mostra o menu do sistema
                                    //}
                                    //else
                                    //{
                                     //   Utilitarios.mostraNaTela("Confirmação de senha errada \nTente Novamente");
                                       // confirmacaoErrada = false;
                                    //}

                                }
                                else//não cadastra usuario
                                {
                                    Utilitarios.mostraNaTela("Usuario NÃO cadastrado!!");
                                }
                            }
                            else//O USUARIO JA EXISTE logo sua senha e a mesma coisa q a confirmação da senha, metodo gravarArquivo
                            {
                                //Utilitarios.mostraNaTela("Digite a senha");
                                   // sSenha = pegaInformacao.nextLine();
                                    boolean senhaCorreta = Utilitarios.carregaParametros(tf_usuario.getText(), tf_senha.getText());
                                    if (senhaCorreta == true)
                                    {
                                        //Utilitarios.mostraNaTela("Seu ultimo acesso foi: ");
                                        Utilitarios.carregaParametrosDataHora(tf_usuario.getText()); //mostra ultimo acesso
                                        Utilitarios.gravaArquivo(tf_usuario.getText(), tf_senha.getText(), tf_senha.getText());//grava usuario senha confirmação da senha
                                        // e ultimo acesso
                                        //Utilitarios.mostraMenuDe5opcoes();// mostra o menu do sistema
                                        //byte sMenuOpcao = pegaInformacao.nextByte(); // pega a opção de 1 a 5
                                        Menu1a5.opcoes(tf_usuario.getText()); // joga a opção para o metodo
                                        //confirmacaoErrada = true; 
                                    }
                                    else
                                    {
                                        Utilitarios.mostraNaTela("Senha Incorreta \nTente Novamente");
                                        //confirmacaoErrada = false;
                                    }
                            }
                    //}while(confirmacaoErrada == false);
            }
            
    }//GEN-LAST:event_bt_entrarActionPerformed

    private void tf_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_usuarioActionPerformed
        //esse evento acontece quando pressiona enter
        
        // TODO add your handling code here:
        //tf_usuario.setText("digite sua se");
        //tf_usuario.selectAll();
        
    }//GEN-LAST:event_tf_usuarioActionPerformed

    private void foco(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_foco
        // TODO add your handling code here:
        tf_usuario.selectAll();
        tf_senha.selectAll();
    }//GEN-LAST:event_foco

    private void enter(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enter
        // TODO add your handling code here:
        //if (bt_entrar.getText() == bt_entrar.getText())
        //{
            bt_entrarActionPerformed(null);
        //}
    }//GEN-LAST:event_enter

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_entrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_senha;
    private javax.swing.JLabel lb_usuario;
    private javax.swing.JPasswordField tf_senha;
    private javax.swing.JTextField tf_usuario;
    // End of variables declaration//GEN-END:variables
}
