import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import java.io.File;
import java.io.IOException;

import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import jxl.Cell;
import jxl.Sheet;
import jxl.Workbook;
import jxl.read.biff.BiffException;
/**
 *
 * @author Müller
 */
public class Administracao_Chamado extends javax.swing.JFrame 
{
    static ArrayList celulas = new ArrayList();    
    static int linhas = 0;
    /** Creates new form Administracao_Chamado */
    public Administracao_Chamado() throws BiffException, IOException {
        initComponents();
        setLocationRelativeTo(null);// centraliza tela
        setExtendedState(JFrame.MAXIMIZED_BOTH); //maximiza a tela
        pa_Oi.setVisible(false); // esconde painel   
        preencheTabela();
        
        ta_tabela.setModel(new javax.swing.table.DefaultTableModel
        (
            new Object [][]
            {
                {celulas.get(8).toString(), celulas.get(9).toString(), celulas.get(10).toString(), celulas.get(11).toString(), celulas.get(12), celulas.get(13).toString(), celulas.get(14).toString(), celulas.get(15).toString()},
                
                {celulas.get(16).toString(), celulas.get(17).toString(), celulas.get(18).toString(), celulas.get(19).toString(),celulas.get(20), celulas.get(21).toString().toString(), celulas.get(22).toString(), celulas.get(23).toString()},                

                {celulas.get(24).toString(), celulas.get(25).toString(), celulas.get(26).toString(), celulas.get(27).toString(), celulas.get(28).toString(), celulas.get(29).toString(), celulas.get(30).toString(), celulas.get(31).toString()}
            },
            new String [] 
            {
                celulas.get(0).toString(), celulas.get(1).toString(), celulas.get(2).toString(), celulas.get(3).toString(),
                celulas.get(4).toString(), celulas.get(5).toString(), celulas.get(6).toString(), celulas.get(7).toString()
            }
        ));
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pa_Oi = new javax.swing.JPanel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_tabela = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pa_Oi.setBackground(new java.awt.Color(255, 255, 102));

        jRadioButton3.setText("Protocolo");

        jLabel1.setText("Pesquisar por:");

        jRadioButton5.setText("Hora");

        jButton2.setText("Pesquisar");

        jRadioButton4.setText("Data");

        jRadioButton2.setText("Local");

        jRadioButton1.setText("Link");

        jRadioButton6.setText("Observação");

        ta_tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Link", "Local", "Protocolo", "Data", "Defeito", "Observação"
            }
        ));
        ta_tabela.setPreferredSize(new java.awt.Dimension(100, 64));
        jScrollPane2.setViewportView(ta_tabela);
        ta_tabela.getColumnModel().getColumn(0).setHeaderValue("Link");
        ta_tabela.getColumnModel().getColumn(1).setHeaderValue("Local");
        ta_tabela.getColumnModel().getColumn(2).setHeaderValue("Protocolo");
        ta_tabela.getColumnModel().getColumn(3).setHeaderValue("Data");
        ta_tabela.getColumnModel().getColumn(4).setHeaderValue("Defeito");
        ta_tabela.getColumnModel().getColumn(5).setHeaderValue("Observação");

        jLabel2.setText("Chamado Oi");

        jButton1.setText("Novo Chamado");

        javax.swing.GroupLayout pa_OiLayout = new javax.swing.GroupLayout(pa_Oi);
        pa_Oi.setLayout(pa_OiLayout);
        pa_OiLayout.setHorizontalGroup(
            pa_OiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pa_OiLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pa_OiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pa_OiLayout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addGap(94, 94, 94)
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 1482, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(108, 108, 108))
                    .addGroup(pa_OiLayout.createSequentialGroup()
                        .addGroup(pa_OiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton6)
                            .addComponent(jRadioButton5)
                            .addComponent(jRadioButton4)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton2))
                        .addContainerGap(1741, Short.MAX_VALUE))))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
            .addGroup(pa_OiLayout.createSequentialGroup()
                .addGroup(pa_OiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pa_OiLayout.createSequentialGroup()
                        .addGap(912, 912, 912)
                        .addComponent(jLabel2))
                    .addGroup(pa_OiLayout.createSequentialGroup()
                        .addGap(492, 492, 492)
                        .addComponent(jButton1)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pa_OiLayout.setVerticalGroup(
            pa_OiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pa_OiLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(19, 19, 19)
                .addGroup(pa_OiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pa_OiLayout.createSequentialGroup()
                        .addGroup(pa_OiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jRadioButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton6))
                    .addGroup(pa_OiLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(pa_OiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))))
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(677, Short.MAX_VALUE))
        );

        jMenu1.setText("Chamado");

        jMenuItem1.setText("Oi");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Itautec");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sobre");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pa_Oi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pa_Oi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1936)/2, (screenSize.height-1118)/2, 1936, 1118);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        pa_Oi.setVisible(true);        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administracao_Chamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administracao_Chamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administracao_Chamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administracao_Chamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
//                new Administracao_Chamado().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel pa_Oi;
    private javax.swing.JTable ta_tabela;
    // End of variables declaration//GEN-END:variables
    
    public static void preencheTabela() throws BiffException, IOException 
    {    
        {
            /**
            * Carrega a planilha
            */
            Workbook workbook = Workbook.getWorkbook(new File("exemplo.xls"));
            /**
            * Aqui é feito o controle de qual aba do xls 
            * será realiza a leitura dos dados
            */
            Sheet sheet = workbook.getSheet(0);

            /**
            * Numero de linhas com dados do xls
            */
            linhas = sheet.getRows();

            for(int i = 0; i < linhas; i++)
            {
                Cell celula1 = sheet.getCell(0, i);
                Cell celula2 = sheet.getCell(1, i);
                Cell celula3 = sheet.getCell(2, i);
                Cell celula4 = sheet.getCell(3, i);
                Cell celula5 = sheet.getCell(4, i);
                Cell celula6 = sheet.getCell(5, i);
                Cell celula7 = sheet.getCell(6, i);
                Cell celula8 = sheet.getCell(7, i);

                celulas.add(celula1.getContents());
                celulas.add(celula2.getContents());
                celulas.add(celula3.getContents());
                celulas.add(celula4.getContents());
                celulas.add(celula5.getContents());
                celulas.add(celula6.getContents());
                celulas.add(celula7.getContents());
                celulas.add(celula8.getContents());
            }
            workbook.close(); //fecha o arquivo exemplo.xls
        }
    }
}